config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get 'up' => 'rails/health#show', as: :rails_health_check

  # Defines the root path route ("/")
  root 'flights#index'

  resources :flights, only: %i[index show] do
    resources :bookings, only: %i[new create]
  end
  resources :bookings, only: [:show]
end

app/models/airport.rb
class Airport < ApplicationRecord
  has_many :departing_flights, foreign_key: 'departure_airport_id', class_name: 'Flight'
  has_many :arriving_flights, foreign_key: 'arrival_airport_id', class_name: 'Flight'

  validates :name, :code, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_many :booking_passengers
  has_many :passengers, through: :booking_passengers

  accepts_nested_attributes_for :passengers
end

app/models/booking_passenger.rb
class BookingPassenger < ApplicationRecord
  belongs_to :booking
  belongs_to :passenger
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :departure_airport, class_name: 'Airport'
  belongs_to :arrival_airport, class_name: 'Airport'
  has_many :bookings
  has_many :passengers, through: :bookings

  validates :date, :duration_in_minutes, presence: true

  scope :on_date, ->(date) { where(date: date.beginning_of_day..date.end_of_day) }
  scope :from_airport, ->(airport_id) { where(departure_airport_id: airport_id) }
  scope :to_airport, ->(airport_id) { where(arrival_airport_id: airport_id) }

  def self.search(params)
    flights = all
    flights = flights.from_airport(params[:departure_airport_id]) if params[:departure_airport_id].present?
    flights = flights.to_airport(params[:arrival_airport_id]) if params[:arrival_airport_id].present?
    flights = flights.on_date(params[:flight_date].to_date) if params[:flight_date].present?
    flights
  end
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  has_many :booking_passengers
  has_many :bookings, through: :booking_passengers
  has_many :flights,  through: :bookings

  validates :name, :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def show
    @booking = Booking.find(params[:id])
  end

  def new
    @flight = Flight.find(params[:flight_id])
    @booking = Booking.new(flight: @flight)
    @passengers = Array.new(params[:number_of_passengers].to_i) { @booking.passengers.build }
  end

  def create
    @booking = Booking.new(booking_params)
    if @booking.save
      redirect_to @booking, notice: 'Booking was successfully created.'
    else
      render :new
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:booking_date, :flight_id, passengers_attributes: %i[name email])
  end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @airport_options = Airport.all.map { |airport| [airport.name, airport.id] }
    @passenger_options = [1, 2, 3, 4]
    @date_options = Flight.order(:date).pluck(:date).map { |d| d.to_date }.uniq.map { |d| [d.strftime('%Y-%m-%d'), d] }

    @flights = if params[:search]
                 Flight.search(params).includes(:departure_airport, :arrival_airport)
               else
                 Flight.includes(:departure_airport, :arrival_airport).all
               end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<h1>New Booking</h1>
<p>Flight: <%= @flight.departure_airport.code %> -> <%= @flight.arrival_airport.code %></p>
<p>Date: <%= @flight.date.strftime("%F %T") %></p>

<%= form_with(model: @booking, url: flight_bookings_path(@flight)) do |form| %>
  <%= form.hidden_field :flight_id, value: @flight.id %>
  <%= form.hidden_field :booking_date, value: Time.now %>

  <h2>Passengers</h2>
  <%= form.fields_for :passengers do |passenger_fields| %>
    <div>
      <%= passenger_fields.label :name %>
      <%= passenger_fields.text_field :name %>
    </div>
    <div>
      <%= passenger_fields.label :email %>
      <%= passenger_fields.email_field :email %>
    </div>
  <% end %>

  <%= form.submit %>
<% end %>

app/views/bookings/show.html.erb
<h1>Booking details</h1>
<p>Flight: <%= @booking.flight.departure_airport.code %> -> <%= @booking.flight.arrival_airport.code %></p>
<p>Date: <%= @booking.flight.date.strftime("%F %T") %></p>

<h2>Passengers</h2>
<ul>
  <% @booking.passengers.each do |passenger| %>
    <li>
      <p><%= passenger.name %> <%= passenger.email %></p>
    </li>
  <% end %>
</ul>

app/views/flights/index.html.erb
<h1>Flights Search</h1>

<%= form_with url: flights_path, method: :get do |form| %>
  <div>
    <%= form.label :departure_airport_id, 'Departure airport:' %>
    <%= form.select :departure_airport_id, @airport_options, include_blank: "Choose departure airport", selected: params[:departure_airport_id] %>
  </div>

  <div>
    <%= form.label :arrival_airport_id, 'Arrival airport:' %>
    <%= form.select :arrival_airport_id, @airport_options, include_blank: "Choose arrival airport", selected: params[:arrival_airport_id] %>
  </div>

  <div>
    <%= form.label :flight_date, 'Date:' %>
    <%= form.select :flight_date, @date_options, include_blank: "Choose date", selected: params[:flight_date] %>
  </div>

  <div>
    <%= form.label :number_of_passengers, 'Number of passengers:' %>
    <%= form.select :number_of_passengers, @passenger_options, selected: params[:number_of_passengers] %>
  </div>

  <div>
    <%= form.submit "Search", name: "search" %>
  </div>
<% end %>

<% if @flights.any? %>
  <ul>
    <% @flights.each do |flight| %>
      <li>
      <p><%= flight.departure_airport.code %> -> <%= flight.arrival_airport.code %> Date:<%= flight.date.strftime('%Y-%m-%d') %> Duration:<%= flight.duration_in_minutes %> min</p>
      <%= link_to "Book", new_flight_booking_path(flight_id: flight.id, number_of_passengers: params[:number_of_passengers].presence || 1)%>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>No available flights.</p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinFlightBooker</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>